# Generated by Django 5.1.4 on 2024-12-09 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='Season',
            new_name='season',
        ),
    ]
