# Generated by Django 5.1.4 on 2024-12-10 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_season_transfer_season'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
    ]
